services:
  - type: web
    name: javascript-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: API_PROVIDER
        value: "https://api.multiversx.com"
      - key: CHAIN
        value: "mainnet"
      - key: SECURE_TOKEN
        sync: false
      - key: CHAIN_ID
        value: "1" # Optional, specify if required
    autoDeploy: true
    region: frankfurt
