services:
  - type: web
    name: javascript-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: API_PROVIDER
        value: "https://api.multiversx.com"
      - key: CHAIN
        value: "mainnet"
      - key: SECURE_TOKEN
        value: ""
        sync: true
      - key: CHAIN_ID
        value: "1"
      - key: ADMIN_KEY
        value: ""
        sync: true
    autoDeploy: true
    region: frankfurt
