services:
  - type: web
    name: javascript-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: API_PROVIDER
        value: "https://api.multiversx.com"
      - key: CHAIN
        value: "mainnet"
      - key: SECURE_TOKEN
        value: ""
        sync: true
      - key: CHAIN_ID
        value: "1"
      - key: ADMIN_TOKEN
        value: ""
        sync: true
      - key: LOG_LEVEL
        value: "info"
      - key: WEBHOOK_WHITELIST_URL
        value: ""
      - key: TREASURY_WALLET
        value: ""
    autoDeploy: true
    region: frankfurt
    healthCheckPath: /health
